<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260129125748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mundo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, dificultad VARCHAR(255) NOT NULL, orden INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE nivel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, mapa_json JSON NOT NULL, mundo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AAFC20CB3495D15F ON nivel (mundo_id)');
        $this->addSql('CREATE TABLE progreso (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, puntuacion INT NOT NULL, fecha_completado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT NOT NULL, nivel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3600AE09DB38439E ON progreso (usuario_id)');
        $this->addSql('CREATE INDEX IDX_3600AE09DA3426AE ON progreso (nivel_id)');
        $this->addSql('CREATE TABLE rol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nickname VARCHAR(50) NOT NULL, rol_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2265B05D4BAB96C ON usuario (rol_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE nivel ADD CONSTRAINT FK_AAFC20CB3495D15F FOREIGN KEY (mundo_id) REFERENCES mundo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progreso ADD CONSTRAINT FK_3600AE09DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progreso ADD CONSTRAINT FK_3600AE09DA3426AE FOREIGN KEY (nivel_id) REFERENCES nivel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D4BAB96C FOREIGN KEY (rol_id) REFERENCES rol (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE nivel DROP CONSTRAINT FK_AAFC20CB3495D15F');
        $this->addSql('ALTER TABLE progreso DROP CONSTRAINT FK_3600AE09DB38439E');
        $this->addSql('ALTER TABLE progreso DROP CONSTRAINT FK_3600AE09DA3426AE');
        $this->addSql('ALTER TABLE usuario DROP CONSTRAINT FK_2265B05D4BAB96C');
        $this->addSql('DROP TABLE mundo');
        $this->addSql('DROP TABLE nivel');
        $this->addSql('DROP TABLE progreso');
        $this->addSql('DROP TABLE rol');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
